s = tf('s');
P = 1 / (s * (s+1) * (s+5));
Kp = 30;
C_p = pid(Kp, 0, 0);
T_p = feedback(C_p * P, 1);
figure;
step(T_p);
title('???? ?? ?????? P (Kp=30)');
Ki = 70;
C_pi = pid(Kp, Ki, 0);
T_pi = feedback(C_pi * P, 1);
hold on;
step(T_pi);
title('?????? ???????');
Kd = 15;
C_pid = pid(Kp, Ki, Kd);
T_pid = feedback(C_pid * P, 1);
step(T_pid);
legend('??? P', 'PI', 'PID');
grid on;
