new_system('pid_closed_loop_model');
open_system('pid_closed_loop_model');
add_block('simulink/Sources/Step', 'pid_closed_loop_model/Step');
set_param('pid_closed_loop_model/Step', 'StepTime', '1', 'InitialValue', '0', 'FinalValue', '1');
add_block('simulink/Math Operations/Sum', 'pid_closed_loop_model/Sum');
set_param('pid_closed_loop_model/Sum', 'Inputs', '|+-');
add_block('simulink/Continuous/PID Controller', 'pid_closed_loop_model/PID Controller');
set_param('pid_closed_loop_model/PID Controller', 'Controller', 'PID', 'Form', 'Parallel', 'P', '28.5', 'I', '65.2', 'D', '8.9');
add_block('simulink/Continuous/Transfer Fcn', 'pid_closed_loop_model/Transfer Fcn');
set_param('pid_closed_loop_model/Transfer Fcn', 'Numerator', '[4]', 'Denominator', '[1 2 4]');
add_block('simulink/Signal Routing/Mux', 'pid_closed_loop_model/Mux');
set_param('pid_closed_loop_model/Mux', 'Inputs', '2');
add_block('simulink/Sinks/Scope', 'pid_closed_loop_model/Scope');
add_line('pid_closed_loop_model', 'Step/1', 'Sum/1', 'autorouting', 'on');
add_line('pid_closed_loop_model', 'Sum/1', 'PID Controller/1', 'autorouting', 'on');
add_line('pid_closed_loop_model', 'PID Controller/1', 'Transfer Fcn/1', 'autorouting', 'on');
add_line('pid_closed_loop_model', 'Transfer Fcn/1', 'Sum/2', 'autorouting', 'on');
add_line('pid_closed_loop_model', 'Transfer Fcn/1', 'Mux/1', 'autorouting', 'on');
add_line('pid_closed_loop_model', 'Step/1', 'Mux/2', 'autorouting', 'on');
add_line('pid_closed_loop_model', 'Mux/1', 'Scope/1', 'autorouting', 'on');
set_param('pid_closed_loop_model', 'StopTime', '10');
sim('pid_closed_loop_model');
